name: CI - integration test install-command input

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: ./.github/workflows/nx-cloud-main.yml
    with:
      working-directory: ./integration-tests/npm
      install-commands: |
        echo "Installing dependencies with custom install-commands"
        npm ci
        touch ./install-commands-success
        echo "install commands end"
      parallel-commands: |
        node -e "const f = require('fs'); if(f.existsSync('./install-commands-success')) console.log('install-commands success'); else { throw new Error('install commands did not run!');}"
        npx nx format:check
      parallel-commands-on-agents: |
        node -e "const f = require('fs'); if(f.existsSync('./install-commands-success')) console.log('install-commands success on agent.'); else { throw new Error('install commands did not run!');}"
        npx node --max_old_space_size=8048 ./node_modules/.bin/nx affected --target=lint --parallel=3
        npx node --max_old_space_size=8048 ./node_modules/.bin/nx affected --target=test --parallel=3 --ci --code-coverage
        npx node --max_old_space_size=8048 ./node_modules/.bin/nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: ./.github/workflows/nx-cloud-agents.yml
    with:
      working-directory: ./integration-tests/npm
      number-of-agents: 3
      install-commands: |
        echo "Installing dependencies with custom install-commands"
        npm ci
        touch ./install-commands-success
        echo "install commands end"
